"""
Django settings for super_express project.

Generated by 'django-admin startproject' using Django 3.2.10.

For more information on this file, see
https://docs.djangoproject.com/en/3.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.2/ref/settings/
"""

from email import message
from logging import warning
from pathlib import Path
import os
from pyexpat.errors import messages
from django.contrib.messages import constants as messages

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

#######################
    # Added by Sharjil
#######################

SETTINGS_FILE_NAME='local_settings'
ENV_TYPE='dev'
WWW_SITE='http://127.0.0.1:8000'


MESSAGE_TAGS={
messages.INFO : 'alert-info',
messages.DEBUG :'alert-info',
messages.SUCCESS :'alert-success',
messages.WARNING :'alert-warning',
messages.ERROR :'alert-danger',

}

AUTH_USER_MODEL = 'accounts_engine.CustomUser'
LOGIN_REDIRECT_URL = '/account/dashboard/'
LOGOUT_REDIRECT_URL = '/account/login/'
CRISPY_TEMPLATE_PACK = 'bootstrap4'

#######################
    # Added by Sharjil
#######################

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-q#l238+=&1187$$yvn5qwi(^rl$xyf)e45+mi&&xm64g#($=1e'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'crispy_forms',
    'accounts_engine',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'super_express.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': ['templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'accounts_engine.custom_processor.general_details',
            ],
        },
    },
]

WSGI_APPLICATION = 'super_express.wsgi.application'


# Database
# https://docs.djangoproject.com/en/3.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'super_express',
        'HOST':'127.0.0.1',
        'USER':'root',
        'PASSWORD':'zara',
        'PORT':3306
    },
    'New': {
         'ENGINE': 'django.db.backends.postgresql',
         'NAME': 'super_express_db',
         'USERNAME':'postgres',
         'PASSWORD': 'Allah@143',
         'HOST':'127.0.0.1',
         'PORT':'5432',
    }
    }

# Password validation
# https://docs.djangoproject.com/en/3.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/3.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Asia/kolkata'

USE_I18N = True

USE_L10N = False

USE_TZ = False


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.2/howto/static-files/

STATIC_URL = '/static/'
STATIC_DIR= os.path.join(BASE_DIR,'static')
STATICFILES_DIRS=[STATIC_DIR]

MEDIA_URL='/media/'
MEDIA_DIR=os.path.join(BASE_DIR,'media')
MEDIAFILES_DIRS=[MEDIA_DIR]



# Default primary key field type
# https://docs.djangoproject.com/en/3.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

